LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := program
LOCAL_C_INCLUDES := $(LOCAL_PATH)/../INCLUDE
LOCAL_SRC_FILES := \
	graclus.c io.c
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)

include $(BUILD_STATIC_LIBRARY)